parameters:
  - name: AppName
    type: string
    default: 'NoName'
  - name: AzureSubscription
    type: string
    default: ''
  - name: Environment
    type: string
    default: 'Staging'
  - name: 'AutoDeploy'
    type: boolean
    default: false
  - name: 'PreviousStage'
    type: string
    default: 'Build_Release'
  - name: 'DeploymentToken'
    type: string
    default: ''

stages:
- stage: Deploy_${{ parameters.Environment}}
  condition: succeeded()
  dependsOn: '${{ parameters.PreviousStage}}'
  jobs:
  - job: waitForValidation
    displayName: Wait for external validation
    pool: server
    timeoutInMinutes: 100 # job times out in 3 days
    steps:
    - task: ManualValidation@0
      condition: eq(${{ parameters.AutoDeploy}}, false)
      timeoutInMinutes: 60 # task times out in 1 day
      inputs:
        notifyUsers: |
          $(Build.RequestedForEmail)
        instructions: 'Veuillez valider la mise en production du site'
        onTimeout: 'reject'

  - deployment: 'Deploy_${{ parameters.Environment}}'
    dependsOn: waitForValidation
    pool: 'windows-latest'
    displayName: 'Deploy the web application to ${{ parameters.Environment}}'
    environment:
      name: ${{ parameters.Environment}}
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureStaticWebApp@0
            inputs:
              app_location: 'src' # App source code path relative to cwd
              api_location: 'api' # Api source code path relative to cwd
              output_location: 'public' # Built app content directory relative to app_location - optional
              cwd: '$(System.DefaultWorkingDirectory)/myapp' # Working directory - optional
              azure_static_web_apps_api_token: $(deployment_token)