parameters:
  - name: WebSiteName
    type: string
    default: 'TestWebSites'
  - name: WebAppName
    type: string
    default: ''
  - name: Environment
    type: string
    default: 'Test'
  - name: 'AutoDeploy'
    type: boolean
    default: false
  - name: PreviousBuildConfiguration
    type: string
    default: 'Release'

stages:
- stage: Deploy${{ parameters.Environment}}
  condition: succeeded()
  dependsOn: Build_Release
  jobs:
  - job: waitForValidation
    displayName: Wait for external validation
    pool: server
    timeoutInMinutes: 100 # job times out in 3 days
    steps:
    - task: ManualValidation@0
      condition: eq(${{ parameters.AutoDeploy}}, false)
      timeoutInMinutes: 60 # task times out in 1 day
      inputs:
        notifyUsers: |
          $(Build.RequestedForEmail)
        instructions: 'Veuillez valider la mise en production du site'
        onTimeout: 'reject'
  - deployment: 'Deploy${{ parameters.Environment}}'
    dependsOn: waitForValidation
    displayName: 'Deploy the web application to ${{ parameters.Environment}}'
    environment:
      name: ${{ parameters.Environment}}
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop           

          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'IIS Web App Deploy'
            inputs:
              WebSiteName: '${{ parameters.WebSiteName}}'
              VirtualApplication: '${{ parameters.WebAppName}}'
              Package: '$(Pipeline.Workspace)\drop\*.zip'
              RemoveAdditionalFilesFlag: true
              TakeAppOfflineFlag: true
              XmlTransformation: true
              XmlVariableSubstitution: true
